import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Hero from '../Components/Hero'
import PinSection from '../Components/PinSection'
import AnimatedSection from '../Components/AnimatedSection'
import Proyects from '../Components/Proyects'
import BackgroundChanger from '../Components/BackgroundChanger'
import FinalSection from '../Components/FinalSection'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Hero/>
        <PinSection/>
        <AnimatedSection/>
        <Proyects/>
        <BackgroundChanger/>
        <FinalSection/>
      </main>
    </>
  )
}
